### ISSUE TITLE
Resizing game window breaks in-game UI buffers

### ISSUE THREAD

**Issue by goaaats** [goaaats/Dalamud#38]
![image](https://user-images.githubusercontent.com/16760685/75459885-16d8f200-59c4-11ea-8c26-6048b262195f.png)
![image](https://user-images.githubusercontent.com/16760685/75459915-20625a00-59c4-11ea-9239-bd6a3acf4145.png)

Can reproduce this locally, with newest GShade.

**Comment by ff-meli** [comment]
Hnadling ResizeBuffers() properly didn't seem to have any effect on this.  It seems like maybe ImGui is not properly resizing its clip/scissor rects, and is also for some reason applying them to the ui layer, which generally shouldn't happen because of the state backup and restore.

ImGui in general seems to not really support resizing well except in an experimental branch.  I don't think we can really tear down and rebuild the whole thing, because that would likely break state for any ui that is currently open.  Will play with it more later.

**Comment by ff-meli** [comment]
Should be fixed in that PR.  Make sure to update the submodule too, as half the changes are there.

**Comment by goaaats** [comment]
Thanks a lot!
